### ISSUE TITLE
What needs to be done to use doubles instead of floats?

### ISSUE THREAD

**Issue by kiwih** [mhogg/octree#46]
Hi,
In the examples the rays are computed over float32s. I notice that in the C++ code mostly it refers to double-type floats. Is there any reason for the discrepancy? Can a version of this be made that uses doubles everywhere instead of some float32s?

**Comment by mhogg** [comment]
Hi kiwih,

I have made a few changes to pyoctree.pyx in the `dev` branch. Essentially just needed to change float to float64. I have tested the changes in the example notebooks.

Now if you want to use rays, you no longer need to use dtype=np.float32. For example (from the readme):
```python
import numpy as np
startPoint = [0.0,0.0,0.0]
endPoint   = [0.0,0.0,1.0]
rayList    = np.array([[startPoint,endPoint]],dtype=np.float32)
intersectionFound  = tree.rayIntersection(rayList)
```
now becomes
```python
import numpy as np
startPoint = [0.0,0.0,0.0]
endPoint   = [0.0,0.0,1.0]
rayList    = np.array([[startPoint,endPoint]])
intersectionFound  = tree.rayIntersection(rayList)
```
Cheers,
Michael

**Comment by kiwih** [comment]
Great, thanks!

**Comment by shashankIITK** [comment]
> Hi kiwih,
> 
> I have made a few changes to pyoctree.pyx in the `dev` branch. Essentially just needed to change float to float64. I have tested the changes in the example notebooks.
> 
> Now if you want to use rays, you no longer need to use dtype=np.float32. For example (from the readme):
> 
> ```python
> import numpy as np
> startPoint = [0.0,0.0,0.0]
> endPoint   = [0.0,0.0,1.0]
> rayList    = np.array([[startPoint,endPoint]],dtype=np.float32)
> intersectionFound  = tree.rayIntersection(rayList)
> ```
> 
> now becomes
> 
> ```python
> import numpy as np
> startPoint = [0.0,0.0,0.0]
> endPoint   = [0.0,0.0,1.0]
> rayList    = np.array([[startPoint,endPoint]])
> intersectionFound  = tree.rayIntersection(rayList)
> ```
> 
> Cheers,
> Michael

I have downloaded source code from dev version of this repository and tried to use it without specifying dtype=np.float32 and only giving start and end points to function to find intersection. It shows error as: 
"Buffer dtype mismatch, expected 'float' but got 'double'.

This error I am getting even after installing and running dev version.
Also in dev version I had to manually insert pyoctree.cpp file as it is not there in source code on github and my system was giving error that missing pyoctree/pyoctree.cpp file.
Kindly tell me what is going wrong in my case.
